//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.EncuestaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EncuestaService.IEncuestaService")]
    public interface IEncuestaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/ListarEncuestasPorUsuario", ReplyAction="http://tempuri.org/IEncuestaService/ListarEncuestasPorUsuarioResponse")]
        System.Collections.Generic.List<BAL.Encuesta> ListarEncuestasPorUsuario(int UsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/ListarPreguntasDisponibles", ReplyAction="http://tempuri.org/IEncuestaService/ListarPreguntasDisponiblesResponse")]
        System.Collections.Generic.List<BAL.GrupoPregunta> ListarPreguntasDisponibles(int FormularioID, int EncuestaNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/ObtenerPreguntas", ReplyAction="http://tempuri.org/IEncuestaService/ObtenerPreguntasResponse")]
        System.Collections.Generic.List<BAL.Formulario> ObtenerPreguntas(int FormularioID, int GrupoPreguntaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/GuardarEncuesta", ReplyAction="http://tempuri.org/IEncuestaService/GuardarEncuestaResponse")]
        int GuardarEncuesta(int ProyectoID, int FormularioID, string CorreoElectronico, int UsuarioAuditID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/GuardarPregunta", ReplyAction="http://tempuri.org/IEncuestaService/GuardarPreguntaResponse")]
        int GuardarPregunta(int ProyectoID, int FormularioID, int TipoPreguntaID, int PreguntaID, int OpcionID, int UsuarioAuditID, int EncuestaNo, string TextoRespuesta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/VerificarUsuario", ReplyAction="http://tempuri.org/IEncuestaService/VerificarUsuarioResponse")]
        int VerificarUsuario(string CorreoElectronico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/ObtenerUsuario", ReplyAction="http://tempuri.org/IEncuestaService/ObtenerUsuarioResponse")]
        BAL.UsuarioEncuesta ObtenerUsuario(int UsuarioEncuestaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/ActualizarUsuarioEncuesta", ReplyAction="http://tempuri.org/IEncuestaService/ActualizarUsuarioEncuestaResponse")]
        int ActualizarUsuarioEncuesta(int UsuarioEncuestaID, string PrimerNombre, string SegundoNombre, string PrimerApellido, string SegundoApellido, string NombreEntidad, string NombreProyecto, string CargoFuncionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/ListarEstatusEncuestasPorUsuario", ReplyAction="http://tempuri.org/IEncuestaService/ListarEstatusEncuestasPorUsuarioResponse")]
        System.Collections.Generic.List<BAL.Encuesta> ListarEstatusEncuestasPorUsuario(int UsuarioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/FinalizarEncuesta", ReplyAction="http://tempuri.org/IEncuestaService/FinalizarEncuestaResponse")]
        int FinalizarEncuesta(int EncuestaNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEncuestaService/SelectPreguntasFaltantes", ReplyAction="http://tempuri.org/IEncuestaService/SelectPreguntasFaltantesResponse")]
        System.Collections.Generic.List<BAL.Pregunta> SelectPreguntasFaltantes(int EncuestaNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEncuestaServiceChannel : WEB.EncuestaService.IEncuestaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncuestaServiceClient : System.ServiceModel.ClientBase<WEB.EncuestaService.IEncuestaService>, WEB.EncuestaService.IEncuestaService {
        
        public EncuestaServiceClient() {
        }
        
        public EncuestaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncuestaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncuestaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncuestaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BAL.Encuesta> ListarEncuestasPorUsuario(int UsuarioID) {
            return base.Channel.ListarEncuestasPorUsuario(UsuarioID);
        }
        
        public System.Collections.Generic.List<BAL.GrupoPregunta> ListarPreguntasDisponibles(int FormularioID, int EncuestaNo) {
            return base.Channel.ListarPreguntasDisponibles(FormularioID, EncuestaNo);
        }
        
        public System.Collections.Generic.List<BAL.Formulario> ObtenerPreguntas(int FormularioID, int GrupoPreguntaID) {
            return base.Channel.ObtenerPreguntas(FormularioID, GrupoPreguntaID);
        }
        
        public int GuardarEncuesta(int ProyectoID, int FormularioID, string CorreoElectronico, int UsuarioAuditID) {
            return base.Channel.GuardarEncuesta(ProyectoID, FormularioID, CorreoElectronico, UsuarioAuditID);
        }
        
        public int GuardarPregunta(int ProyectoID, int FormularioID, int TipoPreguntaID, int PreguntaID, int OpcionID, int UsuarioAuditID, int EncuestaNo, string TextoRespuesta) {
            return base.Channel.GuardarPregunta(ProyectoID, FormularioID, TipoPreguntaID, PreguntaID, OpcionID, UsuarioAuditID, EncuestaNo, TextoRespuesta);
        }
        
        public int VerificarUsuario(string CorreoElectronico) {
            return base.Channel.VerificarUsuario(CorreoElectronico);
        }
        
        public BAL.UsuarioEncuesta ObtenerUsuario(int UsuarioEncuestaID) {
            return base.Channel.ObtenerUsuario(UsuarioEncuestaID);
        }
        
        public int ActualizarUsuarioEncuesta(int UsuarioEncuestaID, string PrimerNombre, string SegundoNombre, string PrimerApellido, string SegundoApellido, string NombreEntidad, string NombreProyecto, string CargoFuncionario) {
            return base.Channel.ActualizarUsuarioEncuesta(UsuarioEncuestaID, PrimerNombre, SegundoNombre, PrimerApellido, SegundoApellido, NombreEntidad, NombreProyecto, CargoFuncionario);
        }
        
        public System.Collections.Generic.List<BAL.Encuesta> ListarEstatusEncuestasPorUsuario(int UsuarioID) {
            return base.Channel.ListarEstatusEncuestasPorUsuario(UsuarioID);
        }
        
        public int FinalizarEncuesta(int EncuestaNo) {
            return base.Channel.FinalizarEncuesta(EncuestaNo);
        }
        
        public System.Collections.Generic.List<BAL.Pregunta> SelectPreguntasFaltantes(int EncuestaNo) {
            return base.Channel.SelectPreguntasFaltantes(EncuestaNo);
        }
    }
}
