//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.CatalogoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogoService.ICatalogoServices")]
    public interface ICatalogoServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServices/CargarCatalogoWCF", ReplyAction="http://tempuri.org/ICatalogoServices/CargarCatalogoWCFResponse")]
        BAL.Catalogo[] CargarCatalogoWCF(string listado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServices/CargarCatalogoDependienteWCF", ReplyAction="http://tempuri.org/ICatalogoServices/CargarCatalogoDependienteWCFResponse")]
        BAL.Catalogo[] CargarCatalogoDependienteWCF(string listado, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoServicesChannel : WEB.CatalogoService.ICatalogoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoServicesClient : System.ServiceModel.ClientBase<WEB.CatalogoService.ICatalogoServices>, WEB.CatalogoService.ICatalogoServices {
        
        public CatalogoServicesClient() {
        }
        
        public CatalogoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BAL.Catalogo[] CargarCatalogoWCF(string listado) {
            return base.Channel.CargarCatalogoWCF(listado);
        }
        
        public BAL.Catalogo[] CargarCatalogoDependienteWCF(string listado, string id) {
            return base.Channel.CargarCatalogoDependienteWCF(listado, id);
        }
    }
}
